### ISSUE TITLE
Bug within Download Function.

### ISSUE THREAD

**Issue by QuaSiMoDooooo** [lrzjbyx/Bilibili_video_convert_pdf#1]
您好，我根据您的readme文件尝试对其它视频进行下载解析，但resource目录下始终下载的为示例视频，导致后续切片分析转换成PDF时仍然是实例视频。我尝试对BilibiliVideoDownloader.py文件进行检查，查看是否有未删除测试信息，但是目前还没有发现问题。

**Comment by QuaSiMoDooooo** [comment]
经测试将原bilibili文件中测试视频删除后，直接放入下载好的指定视频，无论命令行输入什么网址  python main.py --address https://www.bilibili.com/video/XXXX，
均只对放入的指定视频转换。

**Comment by lrzjbyx** [comment]
> 

bilibili网站对api进行了升级，造成接口失效，以至于视频无法下载。

**Comment by lrzjbyx** [comment]
>

**Comment by lrzjbyx** [comment]
> 经测试将原bilibili文件中测试视频删除后，直接放入下载好的指定视频，无论命令行输入什么网址 python main.py --address [https://www.bilibili.com/video/XXXX，](https://www.bilibili.com/video/XXXX%EF%BC%8C) 均只对放入的指定视频转换。

然而并不是仅对案例链接失效，是全网站失效。造成该原因是api失效，大胆猜测一下，bilibili网站对api进行了升级，以至于视频无法下载。

**Comment by lrzjbyx** [comment]
> > 经测试将原bilibili文件中测试视频删除后，直接放入下载好的指定视频，无论命令行输入什么网址 python main.py --address [https://www.bilibili.com/video/XXXX，](https://www.bilibili.com/video/XXXX%EF%BC%8C) 均只对放入的指定视频转换。
> 
> 然而并不是仅对案例链接失效，是全网站失效。造成该原因是api失效，大胆猜测一下，bilibili网站对api进行了升级，以至于视频无法下载。

刚刚核对了api，哔哩哔哩并没有api升级，是代码bug。已修复。

**Comment by lrzjbyx** [comment]
> 经测试将原bilibili文件中测试视频删除后，直接放入下载好的指定视频，无论命令行输入什么网址 python main.py --address [https://www.bilibili.com/video/XXXX，](https://www.bilibili.com/video/XXXX%EF%BC%8C)
> 均只对放入的指定视频转换。

刚刚核对了api，哔哩哔哩并没有api升级，是代码bug。已修复。

**Comment by lrzjbyx** [comment]
> 经测试将原bilibili文件中测试视频删除后，直接放入下载好的指定视频，无论命令行输入什么网址 python main.py --address [https://www.bilibili.com/video/XXXX，](https://www.bilibili.com/video/XXXX%EF%BC%8C)
> 均只对放入的指定视频转换。

猜测是哔哩哔哩升级了API，核对了一下官方接口并没有升级，是代码bug。已修复。

**Comment by QuaSiMoDooooo** [comment]
> 

感谢修复，但测试命令`(Bilibili_video_convert_pdf-main) D:\BIO-INF\python\pycharm\project_casual\Bilibili_video_convert_pdf-main>python main.py --address https://www.bilibili.co
m/video/BV1pa411Y76K
`
提示报错
`FileNotFoundError: [Errno 2] No such file or directory: 'D:\\BIO-INF\\python\\pycharm\\project_casual\\Bilibili_video_convert_pdf-main\\temp\\a542eaa2-7e31
-4e21-b565-cc711e7fe4e0.video`，
手动在项目文件Bilibili_video_convert_pdf-main下创建temp目录，再次尝试命令，
返回异常，
```
《[CSGO]毕设作业 YOLOv5 完美实战》视频音频合并视频！
出现异常!!!
转pdf开始！
文件转换成功！
```
经查源代码发现是combining_video_audio函数下抛出异常信息，猜测是无法检索到手动创建的temp目录下视音文件导致合并失败
`

**Comment by lrzjbyx** [comment]
可在目录下手动创建temp目录

**Comment by lrzjbyx** [comment]
> > 
> 
> 感谢修复，但测试命令`(Bilibili_video_convert_pdf-main) D:\BIO-INF\python\pycharm\project_casual\Bilibili_video_convert_pdf-main>python main.py --address https://www.bilibili.co m/video/BV1pa411Y76K ` 提示报错 `FileNotFoundError: [Errno 2] No such file or directory: 'D:\\BIO-INF\\python\\pycharm\\project_casual\\Bilibili_video_convert_pdf-main\\temp\\a542eaa2-7e31 -4e21-b565-cc711e7fe4e0.video`， 手动在项目文件Bilibili_video_convert_pdf-main下创建temp目录，再次尝试命令， 返回异常，
> 
> ```
> 《[CSGO]毕设作业 YOLOv5 完美实战》视频音频合并视频！
> 出现异常!!!
> 转pdf开始！
> 文件转换成功！
> ```
> 
> 经查源代码发现是combining_video_audio函数下抛出异常信息，猜测是无法检索到手动创建的temp目录下视音文件导致合并失败 `

这个问题是因为ffmpeg库中缺乏可执行文件，问题已修复。
